---
title: "Comparing ZooMSS and ZooMizer"
author: "Patrick Sykes"
output:
  html_document:
    df_print: paged
place: Brisbane
---


```{r setup}
library(mizer)
library(Rcpp)

setwd("~/GitHub/ZooMSS/")
source("fZooMSS_Model.R") #source the model code
source("fZooMSS_CalculatePhytoParam.R")
setwd("~/GitHub/ZooMizer/")
## Build environmental data
enviro <- readRDS("data/enviro_test20.RDS")
enviro_data <- fZooMSS_CalculatePhytoParam(enviro) # Calculate Phytoplankton Parameters
Groups <- read.csv("TestGroups.csv")

input_params <- enviro_data[15,]
input_params$dt <- 1
input_params$tmax <- 1

zoomsstest <- list()
zoomsstest$model$model_runtime <- system.time(
 zoomsstest <- fZooMSS_Model(input_params, Groups, SaveTimeSteps)
)
saveRDS(zoomsstest,"zoomssoutputdt1.rds")
zoomsstest <- readRDS("zoomssoutputdt1.rds")

input_params$tmaxx <- input_params$tmax

source("fZooMizer_run.R")
groups <- read.csv("data/TestGroups_mizer.csv")

zoomizertest <- fZooMizer_run(groups = groups, input = input_params)
```

Let's try and look at some comparisons...

```{r}

#weight vectors
all.equal(zoomsstest$model$param$w, zoomizertest@params@w, check.attributes=FALSE)
all.equal(zoomsstest$model$param$w_phyto, zoomizertest@params@w_full[1:71],check.attributes=FALSE)

#abundances
all.equal(zoomsstest$model$nPP ,zoomizertest@n_pp[1,1:71], check.attributes=FALSE)
all.equal(zoomsstest$model$N[1,,] , zoomizertest@params@initial_n, check.attributes=FALSE)

#senescence mortality
all.equal(zoomsstest$model$M_sb, zoomizertest@params@mu_b, check.attributes=FALSE)


#abundances after a time step?
all.equal(zoomsstest$model$N[2,,] , zoomizertest@n[2,,], check.attributes=FALSE)
```

Consider the search volumes:

```{r}

#zoomss code
SearchVol <- matrix(NA, nrow = zoomsstest$model$param$ngrps, ncol = zoomsstest$model$param$ngrid)
for(i in 1:zoomsstest$model$param$ngrps){
        ### Search volume
    SearchVol[i,] <- (zoomsstest$model$param$Groups$SearchCoef[i])*(zoomsstest$model$param$w^(zoomsstest$model$param$Groups$SearchExp[i]))
    SearchVol[i, 10^(zoomsstest$model$param$Groups$Wmax[i]) < zoomsstest$model$param$w * (1 + 1e-06)] <- 0
    SearchVol[i, 10^(zoomsstest$model$param$Groups$W0[i]) > zoomsstest$model$param$w * (1 - 1e-06)] <- 0
}


all.equal(SearchVol, zoomizertest@params@search_vol, check.attributes=FALSE)


```



How about predation kernels?

```{r}
param <- zoomsstest$model$param
model <- zoomsstest$model
  
  gg_log_t_phyto <- ((param$w^-1) %*% t(param$w_phyto))/log(10) # Growth
  diff_log_t_phyto <- ((param$w^-2) %*% t(param$w_phyto^2))/log(10) # Diffusion
  diet_log_t_phyto <- matrix(param$w_phyto, nrow = length(param$w), ncol = length(param$w_phyto), byrow = TRUE) # Diet/Ingestion

  # Predators are rows, dynam prey weights are columns
  gg_log_t_dynam <- ((param$w^-1) %*% t(param$w))/log(10) # Growth
  diff_log_t_dynam <- ((param$w^-2) %*% t(param$w^2))/log(10) # Diffusion
  diet_log_t_dynam <- matrix(param$w, nrow = length(param$w), ncol = length(param$w), byrow = TRUE) # Diet/ingestion

  ### PREDATION KERNELS FOR PHYTOPLANKTON SPECTRUM AND DYNAMIC SPECTRUM
  phyto_pred_weight_matrix <- matrix(param$w, nrow = param$ngrid, ncol = param$ngridPP)
  dynam_pred_weight_matrix <- matrix(param$w, nrow = param$ngrid, ncol = param$ngrid)
  phyto_prey_weight_matrix <- matrix(param$w_phyto, nrow = param$ngrid, ncol = param$ngridPP, byrow = TRUE)
  dynam_prey_weight_matrix <- matrix(param$w, nrow = param$ngrid, ncol = param$ngrid, byrow = TRUE)

  ## Search Volume storage
  SearchVol <- matrix(NA, nrow = param$ngrps, ncol = param$ngrid) # Search volume

  # Simpson's Rule matrices for growth, diffusion and mortality integrals
  simp_phyto <- array(1, dim = param$ngridPP)
  simp_phyto[c(seq(2, param$ngridPP-1,2))] <- 4
  simp_phyto[c(seq(3, param$ngridPP-1,2))] <- 2
  sm_phyto <- matrix(simp_phyto, nrow = param$ngrid, ncol = param$ngridPP, byrow = TRUE) * (param$dx/3)

  simp_dynam <- array(1, dim = param$ngrid)
  simp_dynam[c(seq(2, param$ngrid-1,2))] <- 4
  simp_dynam[c(seq(3, param$ngrid-1,2))] <- 2
  sm_dynam <- matrix(simp_dynam, nrow = param$ngrid, ncol = param$ngrid, byrow = TRUE) * (param$dx/3)

  ## Temperature Effect Matrix
  # Effect of temperature on feeding and predation rate
  #temp_flag <- 2.4^((environ$sst)/10)
  #temp_cil <- 2.8^((environ$sst)/10)
  #temp_gel <- 1.75^((environ$sst)/10)
  #temp_larv <- 2.2^((environ$sst)/10)
  #temp_chaet <- 2.44^((environ$sst)/10)
  #temp_crust <- 2.57^((environ$sst)/10)
  #temp_ocop <- 2.8^((environ$sst)/10)
  #temp_ccop <- 2.8^((environ$sst)/10)
  #temp_fish <- 2.6^((environ$sst)/10)

  #temp_zoo <- c(temp_flag, temp_cil, temp_larv, temp_ocop, temp_ccop, temp_crust, temp_chaet, temp_larv, temp_gel)
  #temp_fish <- rep(temp_fish, num_fish)

  #temp_zoo <- rep(exp(23.93 - 0.59/(8.62e-05*(273+environ$sst))), num_zoo) # exp(23.93 - 0.59/(8.62e-05*(273+environ$sst)))
  #temp_fish <- rep(exp(23.93 - 0.59/(8.62e-05*(273+environ$sst))), num_fish) # exp(25.55 - 0.63/(8.62e-05*(273+environ$sst)))/exp(23.93 - 0.59/(8.62e-05*(273+environ$sst)))

  ### Q10 OF 2 FOR ALL ZOO AND FISH
  temp_zoo <- rep(2.^((param$sst - 30)/10), param$num_zoo) # exp(23.93 - 0.59/(8.62e-05*(273+environ$sst)))
  temp_fish <- rep(2.^((param$sst - 30)/10), param$num_fish)
  temp_eff <- matrix(c(temp_zoo, temp_fish), nrow = param$ngrps, ncol = param$ngrid)

  #### CALCULATES CONSTANT BITS OF THE MODEL FUNCTIONS FOR EACH GROUP
  for(i in 1:param$ngrps){
    ## Senescence mortality
    if(i < 10){
      model$M_sb[i,] <- param$ZSpre*(param$w/(10^(param$Groups$Wmat[i])))^param$ZSexp
      model$M_sb[i, 10^(param$Groups$Wmax[i]) < param$w] <- 0
      model$M_sb[i, 10^(param$Groups$Wmat[i]) > param$w] <- 0
    }

    if(i > 9){
      model$M_sb[i,] <- 0.1*param$ZSpre*(param$w/(10^(param$Groups$Wmat[i])))^param$ZSexp
      model$M_sb[i, 10^(param$Groups$Wmax[i]) < param$w] <- 0
      model$M_sb[i, 10^(param$Groups$Wmat[i]) > param$w] <- 0
    }

    ### Search volume
    SearchVol[i,] <- (param$Groups$SearchCoef[i])*(param$w^(param$Groups$SearchExp[i]))
    SearchVol[i, 10^(zoomsstest$model$param$Groups$Wmax[i]) < zoomsstest$model$param$w * (1 + 1e-06)] <- 0
    SearchVol[i, 10^(zoomsstest$model$param$Groups$W0[i]) > zoomsstest$model$param$w * (1 - 1e-06)] <- 0

    ### Predation Kernels
    if(is.na(param$Groups$PPMRscale[i]) == FALSE){ # If group has an m-value (zooplankton)
      # Calculate PPMR for zooplankton, which changes according to body-size (Wirtz, 2012)
      D.z <- 2*(3*param$w*1e12/(4*pi))^(1/3) # convert body mass g to ESD (um)
      betas <- (exp(0.02*log(D.z)^2 - param$Groups$PPMRscale[i] + 1.832))^3 # Wirtz's equation
      beta_mat_phyto <- matrix(betas, nrow = param$ngrid, ncol = param$ngridPP)
      beta_mat_dynam <- matrix(betas, nrow = param$ngrid, ncol = param$ngrid)

      # Calculate feeding kernels
      sp_phyto_predkernel <- exp(-0.5*(log((beta_mat_phyto*phyto_prey_weight_matrix)/
                                            phyto_pred_weight_matrix)/param$Groups$FeedWidth[i])^2)/
        sqrt(2*pi*param$Groups$FeedWidth[i]^2)
      sp_dynam_predkernel <- exp(-0.5*(log((beta_mat_dynam*dynam_prey_weight_matrix)/
                                            dynam_pred_weight_matrix)/param$Groups$FeedWidth[i])^2)/
        sqrt(2*pi*param$Groups$FeedWidth[i]^2)

      # The feeding kernal of filter feeders is not expected to change much with increasing size so we fix it here

      # if (param$fixed_filterPPMR == TRUE){
        if(i == 3){
          sp_phyto_predkernel <- matrix(sp_phyto_predkernel[44,], nrow = param$ngrid, ncol = param$ngridPP, byrow = TRUE)
          sp_dynam_predkernel <- matrix(sp_dynam_predkernel[44,], nrow = param$ngrid, ncol = param$ngrid, byrow = TRUE)
        }
        if(i == 8){
          sp_phyto_predkernel <- matrix(sp_phyto_predkernel[61,], nrow = param$ngrid, ncol = param$ngridPP, byrow = TRUE)
          sp_dynam_predkernel <- matrix(sp_dynam_predkernel[61,], nrow = param$ngrid, ncol = param$ngrid, byrow = TRUE)
        }
      # }

    } else { # If group does not have an m-value (fish)
      beta_mat_phyto <- matrix(param$Groups$PPMR[i], nrow = param$ngrid, ncol = param$ngridPP)
      beta_mat_dynam <- matrix(param$Groups$PPMR[i], nrow = param$ngrid, ncol = param$ngrid)

      # Calculate feeding kernels
      sp_phyto_predkernel <- exp(-0.5*(log((beta_mat_phyto*phyto_prey_weight_matrix)/
                                            phyto_pred_weight_matrix)/param$Groups$FeedWidth[i])^2)/
        sqrt(2*pi*param$Groups$FeedWidth[i]^2)
      sp_dynam_predkernel <- exp(-0.5*(log((beta_mat_dynam*dynam_prey_weight_matrix)/
                                            dynam_pred_weight_matrix)/param$Groups$FeedWidth[i])^2)/
        sqrt(2*pi*param$Groups$FeedWidth[i]^2)
    }
    
}

  zoomizerpredkernel <- getPredKernel(zoomizertest@params)
  dim(zoomizerpredkernel)
#all.equal(sp_dynam_predkernel[7,,],zoomizerpredkernel[7,,(216-178+1):216], check.attributes=FALSE) # different dimensions - how to compare?
  
  zoomizerdiet <- getDiet(zoomizeroutput@params, proportion = FALSE) #rowSums(sweep(params@pred_kernel, 3, params@dw_full * params@w_full * n_pp, "*"), dims = 2)
  #zoomssgrid[[1]]
  dim(zoomizerdiet)
  #dimnames(zoomizerdiet)
  #zoomizerdiet[,,13] #rowSums(sweep(params@pred_kernel, 3, params@dw_full * params@w_full * n_pp, "*"), dims = 2)
  dim(zoomsstest$model$phyto_dietkernel)
  all.equal(zoomsstest$model$phyto_dietkernel[1,2,1],zoomsstest$model$phyto_dietkernel[1,2,2])
  all.equal(zoomsstest$model$phyto_dietkernel[,,1]*zoomizertest@n_pp[1,1:178], zoomizerdiet[,,13], check.attributes=FALSE)
  
```

Trying with the actual growth matrices. Mizer uses g/yr as its units. What are the units for ZooMSS?

```{r}
    growth_multiplier <- colSums(model$N[1,,] * model$assim_eff) # 1 x n_sizes
    predation_multiplier <- model$N[1,,] * model$temp_eff # n_species x n_sizes
    #diffusion_multiplier <- colSums(N * (assim_eff^2)) # 1 x n_sizes

    ### DO GROWTH
    dynam_growthkernel <- model$dynam_growthkernel
    dim(dynam_growthkernel) <- c(model$param$ngrps*model$param$ngrid, model$param$ngrid)
    cs <- .colSums(growth_multiplier * t(dynam_growthkernel), m = model$param$ngrid, n = model$param$ngrps*model$param$ngrid)
    dim(cs) <- c(model$param$ngrps, model$param$ngrid)
    gg <- model$ingested_phyto + cs
    
zoomizererepro <- getERepro(zoomizertest@params) #all 0 as expected
zoomizerereprogrowth <- getEReproAndGrowth(zoomizertest@params)
zoomizeregrowth <- getEGrowth(zoomizertest@params)
all.equal(zoomizeregrowth, zoomizerereprogrowth) #should be equal since no energy goes to repro

all.equal(zoomizeregrowth, gg, check.attributes=FALSE) #it was really close earlier with zoomizeregrowth/d/dw, now mizer's N is in 1/g so perhaps this is the right conversion?
```

